#!/bin/bash
# 🎯 Snipper Bot - Interactive Setup Wizard

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     🚀 SNIPPER BOT - SETUP WIZARD 🚀              ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════╝${NC}"
echo ""

# Check Node.js
echo -e "${YELLOW}📋 Checking requirements...${NC}"
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found!${NC}"
    echo "Install from: https://nodejs.org/"
    exit 1
fi
echo -e "${GREEN}✅ Node.js $(node --version) found${NC}"

# Install dependencies
echo ""
echo -e "${YELLOW}📦 Installing dependencies...${NC}"
npm install 2>/dev/null
echo -e "${GREEN}✅ Dependencies installed${NC}"

# Create .env file
echo ""
echo -e "${YELLOW}⚙️  Configuration Wizard${NC}"
echo "=============================="

# Function to prompt for input
prompt_input() {
    local label=$1
    local default=$2
    local is_secret=$3
    
    echo ""
    if [ -n "$default" ]; then
        if [ "$is_secret" == "true" ]; then
            read -s -p "  $label [$default]: " value
            echo ""
        else
            read -p "  $label [$default]: " value
        fi
    else
        if [ "$is_secret" == "true" ]; then
            read -s -p "  $label: " value
            echo ""
        else
            read -p "  $label: " value
        fi
    fi
    
    if [ -z "$value" ]; then
        echo "$default"
    else
        echo "$value"
    fi
}

# Generate .env content
echo ""
echo -e "${YELLOW}🔐 Setting up your trading configuration...${NC}"
echo ""

# Wallet setup
echo -e "${BLUE}1️⃣  Wallet Setup${NC}"
echo "   You need a Solana wallet to trade."
echo "   Options:"
echo "   [1] I have a private key"
echo "   [2] Generate new wallet"
read -p "   Choice: " wallet_choice

if [ "$wallet_choice" == "2" ]; then
    echo ""
    echo -e "${YELLOW}🔑 Generating new wallet...${NC}"
    PRIVATE_KEY=$(node -e "
const { Keypair } = require('@solana/web3.js');
const kp = Keypair.generate();
console.log(JSON.stringify(Array.from(kp.secretKey)));
" 2>/dev/null)
    
    if [ -z "$PRIVATE_KEY" ]; then
        echo -e "${RED}❌ Failed to generate wallet. Using placeholder.${NC}"
        PRIVATE_KEY="[your-private-key]"
    else
        echo -e "${GREEN}✅ Wallet generated!${NC}"
        echo -e "${YELLOW}⚠️  IMPORTANT: Save this key safely!${NC}"
    fi
else
    PRIVATE_KEY=$(prompt_input "Enter your private key (base58)" "[your-private-key]" "true")
fi

# RPC Setup
echo ""
echo -e "${BLUE}2️⃣  RPC Setup${NC}"
echo "   For best performance, get a free key from https://helius.xyz"
RPC_URL=$(prompt_input "RPC URL" "https://api.mainnet-beta.solana.com" "false")
HELIUS_API_KEY=$(prompt_input "Helius API Key (optional)" "" "true")

# Telegram (optional)
echo ""
echo -e "${BLUE}3️⃣  Telegram Notifications (optional)${NC}"
echo "   Create a bot at https://t.me/BotFather"
TELEGRAM_BOT_TOKEN=$(prompt_input "Telegram Bot Token" "" "true")
TELEGRAM_CHAT_ID=$(prompt_input "Telegram Chat ID" "" "false")

# Trading settings
echo ""
echo -e "${BLUE}4️⃣  Trading Settings${NC}"
MAX_POSITION=$(prompt_input "Max position (SOL)" "0.002")
AUTO_TRADE=$(prompt_input "Auto-trade? (true/false)" "false")

# Write .env file
echo ""
echo -e "${YELLOW}💾 Saving configuration...${NC}"
cat > .env << EOF
# Generated by Snipper Bot Setup Wizard
# $(date)

# Wallet
PRIVATE_KEY=$PRIVATE_KEY

# RPC
RPC_URL=$RPC_URL
HELIUS_API_KEY=$HELIUS_API_KEY

# Telegram
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID

# Trading
MAX_POSITION_SOL=$MAX_POSITION
DEFAULT_POSITION_SOL=$MAX_POSITION
AUTO_TRADE=$AUTO_TRADE
EOF

echo -e "${GREEN}✅ Configuration saved to .env${NC}"

# Final instructions
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              🎉 SETUP COMPLETE! 🎉                ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "   1. Start trading: ${GREEN}npm start${NC}"
echo "   2. Dry run mode:  ${GREEN}npm run dry-run${NC}"
echo ""
echo -e "${RED}⚠️  IMPORTANT:${NC}"
echo "   • Never share your .env file"
echo "   • Only fund wallet with what you can afford to lose"
echo "   • Start with small positions"
echo ""
echo -e "${BLUE}📖 See README.md for full documentation${NC}"
