@echo off
chcp 65001 >nul
REM 🎯 Snipper Bot - Windows Setup

echo.
echo ╔════════════════════════════════════════════════════╗
echo ║     🚀 SNIPPER BOT - WINDOWS SETUP 🚀          ║
echo ╚════════════════════════════════════════════════════╝
echo.

REM Check Node.js
where node >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Node.js not found!
    echo Please install from: https://nodejs.org/
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('node --version') do set NODE_VERSION=%%i
echo ✅ Node.js %NODE_VERSION% found
echo.

REM Install dependencies
echo 📦 Installing dependencies...
npm install >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Failed to install dependencies
    echo Try running: npm install
    pause
    exit /b 1
)
echo ✅ Dependencies installed
echo.

REM Create .env file
echo ⚙️  Configuration Wizard
echo ==============================
echo.

echo 🔐 Wallet Setup
echo    You need a Solana wallet to trade.
echo    Options:
echo    [1] I have a private key
echo    [2] Generate new wallet
set /p wallet_choice="   Choice (1/2): "

if "%wallet_choice%"=="2" (
    echo.
    echo 🔑 Generating new wallet...
    node -e "
    const { Keypair } = require('@solana/web3.js');
    const kp = Keypair.generate();
    console.log(JSON.stringify(Array.from(kp.secretKey)));
    " > wallet_temp.txt
    set /p PRIVATE_KEY=<wallet_temp.txt
    del wallet_temp.txt >nul 2>&1
    echo ✅ Wallet generated!
    echo ⚠️  IMPORTANT: Save this key safely!
    echo.
) else (
    set /p PRIVATE_KEY="   Enter your private key (base58): "
    echo.
)

REM RPC Setup
echo 2️⃣  RPC Setup
echo    For best performance, get a free key from https://helius.xyz
set /p RPC_URL="   RPC URL (press Enter for default): "
if "%RPC_URL%"=="" set RPC_URL=https://api.mainnet-beta.solana.com
set /p HELIUS_API_KEY="   Helius API Key (optional): "
echo.

REM Telegram (optional)
echo 3️⃣  Telegram Notifications (optional)
echo    Create a bot at https://t.me/BotFather
set /p TELEGRAM_BOT_TOKEN="   Telegram Bot Token (optional): "
set /p TELEGRAM_CHAT_ID="   Telegram Chat ID (optional): "
echo.

REM Trading settings
echo 4️⃣  Trading Settings
set /p MAX_POSITION="   Max position (SOL) [0.002]: "
if "%MAX_POSITION%"=="" set MAX_POSITION=0.002
set /p AUTO_TRADE="   Auto-trade? (true/false) [false]: "
if "%AUTO_TRADE%"=="" set AUTO_TRADE=false
echo.

REM Write .env file
echo 💾 Saving configuration...
(
    echo # Generated by Snipper Bot Setup Wizard
    echo # %date% %time%
    echo.
    echo # Wallet
    echo PRIVATE_KEY=%PRIVATE_KEY%
    echo.
    echo # RPC
    echo RPC_URL=%RPC_URL%
    echo HELIUS_API_KEY=%HELIUS_API_KEY%
    echo.
    echo # Telegram
    echo TELEGRAM_BOT_TOKEN=%TELEGRAM_BOT_TOKEN%
    echo TELEGRAM_CHAT_ID=%TELEGRAM_CHAT_ID%
    echo.
    echo # Trading
    echo MAX_POSITION_SOL=%MAX_POSITION%
    echo DEFAULT_POSITION_SOL=%MAX_POSITION%
    echo AUTO_TRADE=%AUTO_TRADE%
) > .env

echo ✅ Configuration saved to .env
echo.

echo ╔════════════════════════════════════════════════════╗
echo ║              🎉 SETUP COMPLETE! 🎉            ║
echo ╚════════════════════════════════════════════════════╝
echo.
echo 📖 Next steps:
echo    1. Start trading:  npm start
echo    2. Dry run mode:  npm run dry-run
echo.
echo ⚠️  IMPORTANT:
echo    • Never share your .env file
echo    • Only fund wallet with what you can afford to lose
echo    • Start with small positions
echo.
echo 📚 See README.md for full documentation
echo.
pause
